AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MNISTServiceRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: mnist-service
Outputs:
  MNISTServiceArn:
     Value: !GetAtt MNISTServiceRepo.Arn
     Export:
       Name: MNISTServiceArn